StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60DE706B8166A069}" {
   Id "SPC-Vehicle_M1126_Name"
   Target_en_us "M1126"
   Target_de_de "Transportpanzer \"M1126 Stryker\""
   Target_ru_ru "БТР М1126 \"Stryker\""
   Modified 1693474374
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B8593A19E}" {
   Id "SPC-Vehicle_M1127_Name"
   Target_en_us "M1127"
   Target_de_de "Gepanzertes Aufklärungsfahrzeug \"M1127\""
   Target_ru_ru "БРМ М1127 \"Reconnaissance Vehicle\""
   Modified 1693474378
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B8BA06189}" {
   Id "SPC-Vehicle_M1128_Name"
   Target_en_us "M1128"
   Target_de_de "Leichter Waffenträger \"M1128\""
   Target_ru_ru "БМТВ М1128 \"Mobile Gun System\""
   Modified 1693474382
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B8F0C5512}" {
   Id "SPC-Vehicle_M1129_Name"
   Target_en_us "M1129"
   Target_de_de "Mörserträger \"M1129\""
   Target_ru_ru "Самоходный миномёт М1129 \"Mortar Carrier Vehicle\""
   Modified 1693474386
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B8C7B1B9E}" {
   Id "SPC-Vehicle_M1130_Name"
   Target_en_us "M1130"
   Target_de_de "Mobiler Befehlsstand \"M1130\""
   Target_ru_ru "КШМ М1130 \"Command Vehicle\""
   Modified 1693474390
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B933A2034}" {
   Id "SPC-Vehicle_M1131_Name"
   Target_en_us "M1131"
   Target_de_de "Feuerunterstützungs-Fahrzeug \"M1131\""
   Target_ru_ru "БРД М1131 \"Fire Support Vehicle\""
   Modified 1693474394
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B90B7F62F}" {
   Id "SPC-Vehicle_M1132_Name"
   Target_en_us "M1132"
   Target_de_de "Pionierfahrzeug \"M1132\""
   Target_ru_ru "ИМЗ М1132 \"Engineer Squad Vehicle\""
   Modified 1693474397
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B95F7B526}" {
   Id "SPC-Vehicle_M1133_Name"
   Target_en_us "M1133"
   Target_de_de "Gepanzerter Medizinische Träger \"M1133\""
   Target_ru_ru "БММ М1133 \"Medical Evacuation Vehicle\""
   Modified 1693474400
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B94BFD608}" {
   Id "SPC-Vehicle_M1134_Name"
   Target_en_us "M1134"
   Target_de_de "Leichter-Panzerjaeger \"M1134\" mit Waffensystem \"TOW-2\""
   Target_ru_ru "БМП с ПТУР М1134 \"Anti-Tank Guided Missile Vehicle\""
   Modified 1693474405
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706B995590E0}" {
   Id "SPC-Vehicle_M1135_Name"
   Target_en_us "M1135"
   Target_de_de "ABC-Abwehrfahrzeug \"M1135\""
   Target_ru_ru "Машина РХБ разведки М1135 \"NBCR\""
   Modified 1693474409
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60DE706BBF401F9A}" {
   Id "SPC-Vehicle_M1296_Name"
   Target_en_us "M1296"
   Target_de_de "Radschützenpanzer \"M1296 Stryker Dragoon\""
   Target_ru_ru "БМП М1296 \"Stryker Dragoon\""
   Modified 1693474413
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{63293C7009146892}" {
   Id "SPC-VehiclePart_Cage"
   Target_en_us "Cage"
   Target_de_de "Käfigpanzerung"
   Modified 1663649913
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{63293C700D523FF1}" {
   Id "SPC-Weapon_CROWS"
   Target_en_us "CROWS"
   Target_de_de "FLW"
   Modified 1663650240
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F059F71919BC69}" {
   Id "SPC-Weapon_FGM147"
   Target_en_us "FGM147"
   Modified 1693475617
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{63293C73794BF8BE}" {
   Id "SPC-Weapon_M2HB"
   Target_en_us "M2HB"
   Modified 1663650250
   Author "mikia"
   LastChanged "mikia"
  }
 }
}